modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/paulevsGitch/BetterNether/issues" #optional
[[mods]] #mandatory
modId="betternether" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Better Nether" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/betternether" #optional

logoFile="icon.png" #optional
credits="paulevs (programming, art, ideas, ru/en translations),edos_ (builder, design help)" #optional
authors="Paulevs (Fabric) RedRoseWarrior (Forge)" #optional
description='''
Mod that improves Nether
'''
[[dependencies.betternether]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.betternether]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
